// GERADO por scripts/harvest-vtex-catalog.mts em 2026-09-28 a partir da
// API pública de https://www.creamy.com.br (dados reais: nome/preço/URL/imagem verbatim; disponíveis no momento
// da coleta). Preço é referência de vitrine — no concierge a autoridade é a cotação do operador.
// Para atualizar: node --import tsx scripts/harvest-vtex-catalog.mts https://www.creamy.com.br creamy /tmp/lia-catalog-HaGx92/creamy.ts
import type { CatalogItem } from "./types";

export const CATALOG: CatalogItem[] = [
 {
  sku: "creamy-11",
  name: "Gel-creme Hidratante Calmante - Calming Cream",
  brand: "Creamy",
  unitPrice: 54.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158228/calming-cream-calmante-creamy-1.jpg?v=639072072652100000",
  productUrl: "https://www.creamy.com.br/creamy-calming-cream-1/p",
  popularity: 1
 },
 {
  sku: "creamy-283",
  name: "Clareador - Intense TX",
  brand: "Creamy",
  unitPrice: 149.99,
  unit: "un",
  category: "produtos clareadores",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158464/clareador-intenseTX-creamy-skincare-antimanchas-manchas-melasma-01.jpg?v=639227586107930000",
  productUrl: "https://www.creamy.com.br/intense-tx/p",
  popularity: 2
 },
 {
  sku: "creamy-271",
  name: "Pore Refiner - Suavizador de Poros",
  brand: "Creamy",
  unitPrice: 125.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158385/suavizador-de-poros-pore-refiner-creamy-1.jpg?v=639105659723370000",
  productUrl: "https://www.creamy.com.br/pore-refiner/p",
  popularity: 3
 },
 {
  sku: "creamy-269",
  name: "Ceramide Skin Repair",
  brand: "Creamy",
  unitPrice: 53.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158370/Ceramide-Skin-Repair-1.jpg?v=639096334543800000",
  productUrl: "https://www.creamy.com.br/ceramide-skin-repair/p",
  popularity: 4
 },
 {
  sku: "creamy-259",
  name: "Protetor Solar Watery Fluid FPS 50",
  brand: "Creamy",
  unitPrice: 59.99,
  unit: "un",
  category: "produtos protecao solar",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158163/protetor-solar-watery-fluid-pele-oleosa-FPS50--creamy-1.jpg?v=638989989648000000",
  productUrl: "https://www.creamy.com.br/protetor-solar-watery-fluid-fps-50/p",
  popularity: 5
 },
 {
  sku: "creamy-248",
  name: "Limpador Facial Antioleosidade 300ml",
  brand: "Creamy",
  unitPrice: 54.99,
  unit: "un",
  category: "produtos limpeza facial",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158299/limpador-antioleosidade-salicilico-prebioticos-sabonete-rosto-creamy-1.jpg?v=639096216275030000",
  productUrl: "https://www.creamy.com.br/limpador-facial-antioleosidade-1/p",
  popularity: 6
 },
 {
  sku: "creamy-216",
  name: "Loção Hidratante Fortalecedora - Ceramide Body Cream 200ml",
  brand: "Creamy",
  unitPrice: 44.99,
  unit: "un",
  category: "produtos hidratacao corporal",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158232/200ml-ceramide-body-cream-ceramida-reparador-hidratante-creamy-1.jpg?v=639072074020930000",
  productUrl: "https://www.creamy.com.br/hidratante-corporal-ceramide-200ml/p",
  popularity: 7
 },
 {
  sku: "creamy-213",
  name: "Gel de Limpeza",
  brand: "Creamy",
  unitPrice: 64.99,
  unit: "un",
  category: "produtos limpeza facial",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158253/gel-de-limpeza-verdinho-sabonete-pele-oleosa-creamy-1--1-.jpg?v=639072130527100000",
  productUrl: "https://www.creamy.com.br/gel-de-limpeza/p",
  popularity: 8
 },
 {
  sku: "creamy-170",
  name: "Sérum Antioxidante Clareador - Vitamina C Gold",
  brand: "Creamy",
  unitPrice: 129.99,
  unit: "un",
  category: "produtos antioxidante",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158359/acido-mandelico-creamy-rosinha-1--1-.jpg?v=639096260293330000",
  productUrl: "https://www.creamy.com.br/vitamina-c-gold/p",
  popularity: 9
 },
 {
  sku: "creamy-121",
  name: "Sérum Anti idade - Retinal",
  brand: "Creamy",
  unitPrice: 149.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158325/retinal-retinaldeido-acido-retinoico-clareador-anti-aging-vermelho-creamy-1.jpg?v=639096221799700000",
  productUrl: "https://www.creamy.com.br/serum-facial-anti-aging-retinal-30-g/p",
  popularity: 10
 },
 {
  sku: "creamy-49",
  name: "Protetor Solar Watery Lotion FPS 60",
  brand: "Creamy",
  unitPrice: 69.99,
  unit: "un",
  category: "produtos protecao solar",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158365/protetor-solar-watery-lotion-aquoso-fps60-creamy-1.jpg?v=639096261230500000",
  productUrl: "https://www.creamy.com.br/protetor-solar-fps60-watery-lotion/p",
  popularity: 11
 },
 {
  sku: "creamy-39",
  name: "Creme Clareador para Olhos - Eye Cream",
  brand: "Creamy",
  unitPrice: 139.99,
  unit: "un",
  category: "produtos area dos olhos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158247/eye-cream-area-dos-olhos-olheiras-cinzinha-creamy-1.jpg?v=639072126867530000",
  productUrl: "https://www.creamy.com.br/eye-cream/p",
  popularity: 12
 },
 {
  sku: "creamy-6",
  name: "Sérum Antioxidante - Vitamina C",
  brand: "Creamy",
  unitPrice: 99.99,
  unit: "un",
  category: "produtos antioxidante",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158355/vitamina-c-creamy-antioxidante-1.jpg?v=639096247605930000",
  productUrl: "https://www.creamy.com.br/vitamina-c/p",
  popularity: 13
 },
 {
  sku: "creamy-2",
  name: "Gel Clareador Antiacne - Ácido Mandélico",
  brand: "Creamy",
  unitPrice: 84.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158304/acido-mandelico-creamy-rosinha-1.jpg?v=639096217758800000",
  productUrl: "https://www.creamy.com.br/acido-mandelico/p",
  popularity: 14
 },
 {
  sku: "creamy-276",
  name: "Hydragel Oil Control",
  brand: "Creamy",
  unitPrice: 59.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158437/hidratante-antioleosidade-hydragel-oil-control-creamy-01.png?v=639168689980800000",
  productUrl: "https://www.creamy.com.br/hydragel-oil-control/p",
  popularity: 15
 },
 {
  sku: "creamy-272",
  name: "Creme Antirrugas para Olhos - Retinal Eye Cream",
  brand: "Creamy",
  unitPrice: 134.99,
  unit: "un",
  category: "produtos area dos olhos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158394/antirrugas-para-olhos-retinal-eye-cream-01.png?v=639136068621700000",
  productUrl: "https://www.creamy.com.br/retinal-eye-cream/p",
  popularity: 16
 },
 {
  sku: "creamy-267",
  name: "Sérum Antiacne Acne Defense 5D",
  brand: "Creamy",
  unitPrice: 79.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158195/serum-antiacne-acne-defense-5d-cramy-1.jpg?v=639038163664870000",
  productUrl: "https://www.creamy.com.br/serum-antiacne-acne-defense-5d/p",
  popularity: 17
 },
 {
  sku: "creamy-217",
  name: "Emulsão de Limpeza",
  brand: "Creamy",
  unitPrice: 64.99,
  unit: "un",
  category: "produtos limpeza facial",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158242/emulsao-de-limpeza-rosinha-sabonete-creamy-1.jpg?v=639072125614000000",
  productUrl: "https://www.creamy.com.br/emulsao-de-limpeza/p",
  popularity: 18
 },
 {
  sku: "creamy-116",
  name: "Limpador Facial Glicerinado",
  brand: "Creamy",
  unitPrice: 64.99,
  unit: "un",
  category: "produtos limpeza facial",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158258/limpador-glicerinado-glicerina-sabonete-amarelo-creamy-1.jpg?v=639072131019600000",
  productUrl: "https://www.creamy.com.br/limpador-facial-glicerinado/p",
  popularity: 19
 },
 {
  sku: "creamy-98",
  name: "Sérum Fortalecedor Antioleosidade - Niacinamide B",
  brand: "Creamy",
  unitPrice: 99.99,
  unit: "un",
  category: "produtos clareadores",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158313/niacinamida-vitamina-b-clareador-fortalecedor-antioleosidade-creamy-1.jpg?v=639096220169900000",
  productUrl: "https://www.creamy.com.br/niacinamide-b-complex/p",
  popularity: 20
 },
 {
  sku: "creamy-48",
  name: "Creme Firmador Anti idade - Peptide Cream",
  brand: "Creamy",
  unitPrice: 199.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158319/peptide-cream-biopeptideo-de-cobre-anti-aging-firmeza-creamy-1.jpg?v=639096221160730000",
  productUrl: "https://www.creamy.com.br/antiaging-peptide-cream/p",
  popularity: 21
 },
 {
  sku: "creamy-37",
  name: "Sérum Hidratante com Ácido Hialurônico",
  brand: "Creamy",
  unitPrice: 59.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158344/serum-hidratante-acido-hialuronico-creamy-1.jpg?v=639096227889200000",
  productUrl: "https://www.creamy.com.br/drops-serum-hidratante/p",
  popularity: 22
 },
 {
  sku: "creamy-12",
  name: "Tônico Antioleosidade - Ácido Salicílico",
  brand: "Creamy",
  unitPrice: 99.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158334/tonico-de-acido-salicilico-creamy-antiacne-antioleosidade-1.jpg?v=639096224642530000",
  productUrl: "https://www.creamy.com.br/acido-salicilico-1/p",
  popularity: 23
 },
 {
  sku: "creamy-7",
  name: "Tônico Clareador - Ácido Tranexâmico",
  brand: "Creamy",
  unitPrice: 99.99,
  unit: "un",
  category: "produtos clareadores",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158349/tonico-de-acido-tranexamico-creamy-clareador-melasma-1.jpg?v=639096247087800000",
  productUrl: "https://www.creamy.com.br/acido-tranexamico-5478624/p",
  popularity: 24
 },
 {
  sku: "creamy-3",
  name: "Esfoliante Químico - Ácido Glicólico",
  brand: "Creamy",
  unitPrice: 84.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158269/acido-glicolico-creamy-azulzinho-1.jpg?v=639072135649570000",
  productUrl: "https://www.creamy.com.br/acido-glicolico/p",
  popularity: 25
 },
 {
  sku: "creamy-23",
  name: "Retinol - Creme Corretivo Anti sinais",
  brand: "Creamy",
  unitPrice: 119.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158330/retinol-anti-aging-rugas-roxinho-creamy-1.jpg?v=639096222189870000",
  productUrl: "https://www.creamy.com.br/retinol-1/p",
  popularity: 26
 },
 {
  sku: "creamy-278",
  name: "Duo Antioleosidade - Limpa & Hidrata",
  brand: "Creamy",
  unitPrice: 104.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158443/Duo-Hydragel---Hydragel---1.png?v=639171443974100000",
  productUrl: "https://www.creamy.com.br/duo-antioleosidade-limpa-e-hidrata/p",
  popularity: 27
 },
 {
  sku: "creamy-270",
  name: "Duo Hidratante - Acalma & Repara",
  brand: "Creamy",
  unitPrice: 109.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158380/duo-ceramide-repair-calming-cream-01.png?v=639099575222100000",
  productUrl: "https://www.creamy.com.br/duo-hidratante-acalma-e-repara/p",
  popularity: 28
 },
 {
  sku: "creamy-239",
  name: "Creme de Tratamento Labial - Lip Balm Incolor",
  brand: "Creamy",
  unitPrice: 49.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158119/lip-balm-sem-cor-sem-aroma-hidratante-labial-creamy-1--1-.jpg?v=638949372454530000",
  productUrl: "https://www.creamy.com.br/lip-balm-incolor-1/p",
  popularity: 29
 },
 {
  sku: "creamy-168",
  name: "Loção Hidratante Fortalecedora - Ceramide Body Cream 400ml",
  brand: "Creamy",
  unitPrice: 69.99,
  unit: "un",
  category: "produtos hidratacao corporal",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158237/400ml-ceramide-body-cream-ceramida-reparador-hidratante-creamy-1.jpg?v=639072076482400000",
  productUrl: "https://www.creamy.com.br/hidratante-corporal-ceramide-400ml/p",
  popularity: 30
 },
 {
  sku: "creamy-151",
  name: "Sérum Antiacne Adapalenato",
  brand: "Creamy",
  unitPrice: 129.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158218/serum-adapalenato-adapaleno-antiacne-antioleosidade-lilas-creamy-1.jpg?v=639072063365300000",
  productUrl: "https://www.creamy.com.br/serum-facial-adapalenato/p",
  popularity: 31
 },
 {
  sku: "creamy-134",
  name: "Creme Hidratante Labial - Lip Balm Latte",
  brand: "Creamy",
  unitPrice: 39.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157866/latte-hidratante-labial-lip-balm-volumizador-boca-creamy-1.jpg?v=638901990744100000",
  productUrl: "https://www.creamy.com.br/lip-balm-latte/p",
  popularity: 32
 },
 {
  sku: "creamy-111",
  name: "Duo Protetor Solar + Calming Cream",
  brand: "Creamy",
  unitPrice: 109.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158088/Duo-Protetor-Solar---Calming-Cream.jpg?v=638961286133470000",
  productUrl: "https://www.creamy.com.br/duo-protetor-solar-e-calming-cream/p",
  popularity: 33
 },
 {
  sku: "creamy-85",
  name: "Gel-creme Retexturizador Antioleosidade - Glicointense Peel",
  brand: "Creamy",
  unitPrice: 109.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158263/glicointense-peel-glicolico-salicilico-niacinamida-antiacne-acido-verdinho-creamy-1.jpg?v=639072134144870000",
  productUrl: "https://www.creamy.com.br/glicointense-peel-30-g/p",
  popularity: 34
 },
 {
  sku: "creamy-38",
  name: "Sérum de Prevenção Anti idade",
  brand: "Creamy",
  unitPrice: 79.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158339/serum-anti-aging-linhas-finas-rugas-preventivo-creamy-1.jpg?v=639096225956330000",
  productUrl: "https://www.creamy.com.br/drops-serum-antiaging/p",
  popularity: 35
 },
 {
  sku: "creamy-5",
  name: "Sérum Renovador Suave - Ácido Lático",
  brand: "Creamy",
  unitPrice: 89.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158293/acido-latico-creamy-amarelinho-acne-1.jpg?v=639072139873670000",
  productUrl: "https://www.creamy.com.br/acido-latico/p",
  popularity: 36
 },
 {
  sku: "creamy-286",
  name: "Duo Intense TX + Vitamina C Gold",
  brand: "Creamy",
  unitPrice: 251.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158476/Duo-Intense-TX---Vitamina-C-Gold---1.png?v=639245736868370000",
  productUrl: "https://www.creamy.com.br/intensetx-vitaminacgold/p",
  popularity: 37
 },
 {
  sku: "creamy-285",
  name: "Duo Intense TX + Ceramide Skin Repair",
  brand: "Creamy",
  unitPrice: 188.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158472/Duo-Intense-TX---Ceramide-Skin-Repair---1.png?v=639245711263730000",
  productUrl: "https://www.creamy.com.br/intensetx-ceramideskinrepair/p",
  popularity: 38
 },
 {
  sku: "creamy-280",
  name: "Duo Antiacne - Hidrata & Controla",
  brand: "Creamy",
  unitPrice: 129.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158449/Duo-Hydragel---Acne-Defense---1.png?v=639171477733230000",
  productUrl: "https://www.creamy.com.br/duo-antiacne-hidrata-controla/p",
  popularity: 39
 },
 {
  sku: "creamy-275",
  name: "Duo Retinal - Rosto & Olhos",
  brand: "Creamy",
  unitPrice: 272.48,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158402/Duo-Retinal-Serum-Anti-Idade-e-Creme-Antirrugas-01.png?v=639137147920670000",
  productUrl: "https://www.creamy.com.br/duo-retinal/p",
  popularity: 40
 },
 {
  sku: "creamy-274",
  name: "Duo para Olhos - Clareador e Antirrugas",
  brand: "Creamy",
  unitPrice: 272.48,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158399/Duo-para-Olhos-Clareador-e-Antirrugas-01.png?v=639137148033000000",
  productUrl: "https://www.creamy.com.br/duo-para-olhos-clareador-antirrugas/p",
  popularity: 41
 },
 {
  sku: "creamy-209",
  name: "Duo Anti-Idade - Retinal + Calming Cream",
  brand: "Creamy",
  unitPrice: 179.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158077/dupla-skincare-anti-idade-calming-cream-retinal-creamy-1.jpg?v=638905278224600000",
  productUrl: "https://www.creamy.com.br/duo-retinal-calming-cream/p",
  popularity: 42
 },
 {
  sku: "creamy-136",
  name: "Creme Hidratante Labial - Lip Balm Mocha",
  brand: "Creamy",
  unitPrice: 39.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158055/mocha-hidratante-labial-lip-balm-volumizador-boca-creamy-1.jpg?v=638902592573930000",
  productUrl: "https://www.creamy.com.br/lip-balm-mocha-10g/p",
  popularity: 43
 },
 {
  sku: "creamy-135",
  name: "Creme Hidratante Labial - Lip Balm Chai",
  brand: "Creamy",
  unitPrice: 39.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158059/chai-hidratante-labial-lip-balm-volumizador-boca-creamy-1.jpg?v=638902592639230000",
  productUrl: "https://www.creamy.com.br/lip-balm-chai-10g/p",
  popularity: 44
 },
 {
  sku: "creamy-125",
  name: "Duo Antimanchas - Ácido Mandélico + Ácido Tranexâmico",
  brand: "Creamy",
  unitPrice: 169.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158071/dupla-skincare-antimanchas-mandelico-tranexamico-creamy-1.jpg?v=638905272499900000",
  productUrl: "https://www.creamy.com.br/duo-mandelico-tranexamico/p",
  popularity: 45
 },
 {
  sku: "creamy-94",
  name: "Duo para Poros - Ácido Glicólico + Ácido Mandélico",
  brand: "Creamy",
  unitPrice: 159.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158080/dupla-skincare-poros-acido-mandelico-acido-glicolico-creamy-1.jpg?v=638905279856500000",
  productUrl: "https://www.creamy.com.br/duo-glicolico-e-mandelico/p",
  popularity: 46
 },
 {
  sku: "creamy-90",
  name: "Duo Calming Cream + Gel de Limpeza",
  brand: "Creamy",
  unitPrice: 109.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158108/Duo-Calming-Cream---Gel-de-Limpeza.jpg?v=639084015913800000",
  productUrl: "https://www.creamy.com.br/duo-calming-cream-e-gel-de-limpeza/p",
  popularity: 47
 },
 {
  sku: "creamy-84",
  name: "Calming Body Cream Calming Cream Corporal",
  brand: "Creamy",
  unitPrice: 74.99,
  unit: "un",
  category: "produtos hidratacao corporal",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158223/calming-body-cream-calmante-creamy-1.jpg?v=639072066672800000",
  productUrl: "https://www.creamy.com.br/calming-body-cream/p",
  popularity: 48
 },
 {
  sku: "creamy-58",
  name: "Rotina Acne e Antioleosidade",
  brand: "Creamy",
  unitPrice: 331.54,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158181/Rotina-Antiacne-para-Pele-Oleosa.png?v=639084020673870000",
  productUrl: "https://www.creamy.com.br/rotina-antiacne-oleosa/p",
  popularity: 49
 },
 {
  sku: "creamy-36",
  name: "Creme Hidratante Antivermelhidão - Intensive Cream",
  brand: "Creamy",
  unitPrice: 109.99,
  unit: "un",
  category: "produtos hidratacao",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158282/intensive-cream-rosacea-vermelhidao-acalma-fortalecedor-creamy-1.jpg?v=639072137870000000",
  productUrl: "https://www.creamy.com.br/intensive-repair-cream/p",
  popularity: 50
 },
 {
  sku: "creamy-287",
  name: "Duo Intense TX + Calming Cream",
  brand: "Creamy",
  unitPrice: 184.48,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158480/Duo-Intense-TX---Calming-Cream---1.png?v=639245743196770000",
  productUrl: "https://www.creamy.com.br/intensetx-calmingcream/p",
  popularity: 51
 },
 {
  sku: "creamy-284",
  name: "Duo Intense TX + Peptide Cream",
  brand: "Creamy",
  unitPrice: 314.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158469/Duo-Intense-TX---Peptide-Cream---1.png?v=639245697743800000",
  productUrl: "https://www.creamy.com.br/intensetx-peptide/p",
  popularity: 52
 },
 {
  sku: "creamy-282",
  name: "Rotina de Skincare Jade Picon",
  brand: "Creamy",
  unitPrice: 355.46,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158457/rotina-skincare-jade-picon-creamy-01.jpg?v=639219795795130000",
  productUrl: "https://www.creamy.com.br/rotina-da-jade/p",
  popularity: 53
 },
 {
  sku: "creamy-279",
  name: "Duo Essencial - Pele Oleosa",
  brand: "Creamy",
  unitPrice: 119.88,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158446/Duo-Hydragel---Protetor-Solar---1.png?v=639171462426830000",
  productUrl: "https://www.creamy.com.br/duo-essencial-pele-oleosa/p",
  popularity: 54
 },
 {
  sku: "creamy-268",
  name: "Rotina Antiacne",
  brand: "Creamy",
  unitPrice: 350.4,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158205/rotina-favoritos-creamy-ana-castela-1.jpg?v=639052027539800000",
  productUrl: "https://www.creamy.com.br/rotina-antiacne-creamy/p",
  popularity: 55
 },
 {
  sku: "creamy-233",
  name: "Kit Anti-Manchas",
  brand: "Creamy",
  unitPrice: 322.97,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158486/Kit-Antimanchas---1.png?v=639245938114730000",
  productUrl: "https://www.creamy.com.br/kit-anti-manchas-1/p",
  popularity: 56
 },
 {
  sku: "creamy-226",
  name: "Rotina para Pele Oleosa",
  brand: "Creamy",
  unitPrice: 246.29,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157906/rotina-skincare-pele-oleosa-creamy-1.png?v=638902043882370000",
  productUrl: "https://www.creamy.com.br/rotina-para-pele-oleosa-1/p",
  popularity: 57
 },
 {
  sku: "creamy-129",
  name: "Duo Limpador Glicerinado + Calming Cream",
  brand: "Creamy",
  unitPrice: 109.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158098/Duo-Limpador-Glicerinado---Calming-Cream.jpg?v=639084019118300000",
  productUrl: "https://www.creamy.com.br/duo-limpador-glicerinado-calming-cream/p",
  popularity: 58
 },
 {
  sku: "creamy-112",
  name: "Creme de Reconstrução Capilar Sem Enxágue 50G",
  brand: "Creamy",
  unitPrice: 74.99,
  unit: "un",
  category: "produtos haircare",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158275/01.jpg?v=639072137342030000",
  productUrl: "https://www.creamy.com.br/creme-de-reconstrucao-capilar-sem-enxague/p",
  popularity: 59
 },
 {
  sku: "creamy-108",
  name: "Duo Protetor Solar + Vitamina C",
  brand: "Creamy",
  unitPrice: 159.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158086/Duo-Protetor-Solar---Vitamina-C.jpg?v=639084017309000000",
  productUrl: "https://www.creamy.com.br/duo-protetor-solar-e-vitamina-c/p",
  popularity: 60
 },
 {
  sku: "creamy-100",
  name: "Refil Ácido Glicólico 30g Refil Acido Glicólico 30G - Creamy",
  brand: "Creamy",
  unitPrice: 69.99,
  unit: "un",
  category: "produtos anti-aging",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158026/refil-acido-glicolico-creamy-azulzinho-1.jpg?v=638902582369570000",
  productUrl: "https://www.creamy.com.br/refil-acido-glocolico-30-g/p",
  popularity: 61
 },
 {
  sku: "creamy-99",
  name: "Refil Ácido Mandélico 30g Refil Acido Mandélico 30G - Creamy",
  brand: "Creamy",
  unitPrice: 69.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158018/refil-acido-mandelico-creamy-rosinha-1_.jpg?v=638902581274930000",
  productUrl: "https://www.creamy.com.br/refil-acido-mandelico-30-g/p",
  popularity: 62
 },
 {
  sku: "creamy-92",
  name: "Duo Calming Cream + Retinol",
  brand: "Creamy",
  unitPrice: 149.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158105/Duo-Calming-Cream---Retinol.jpg?v=639084016319870000",
  productUrl: "https://www.creamy.com.br/duo-calming-cream-e-retinol/p",
  popularity: 63
 },
 {
  sku: "creamy-91",
  name: "Duo Calming Cream + Mandélico",
  brand: "Creamy",
  unitPrice: 129.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158107/Duo-Calming-Cream---Mandelico.jpg?v=639084016083230000",
  productUrl: "https://www.creamy.com.br/duo-calming-cream-e-mandelico/p",
  popularity: 64
 },
 {
  sku: "creamy-55",
  name: "Rotina Antimanchas - Pele Oleosa ou Mista Rotina Antimanchas - Oleosa ou mista",
  brand: "Creamy",
  unitPrice: 402.59,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157652/foto-1-Rotina-Antimanchas---para-pele-Oleosa-ou-Mista.png.png?v=638829982920100000",
  productUrl: "https://www.creamy.com.br/antimanchas-oleosa-mista/p",
  popularity: 65
 },
 {
  sku: "creamy-288",
  name: "Duo Intense TX + Ácido Tranexâmico",
  brand: "Creamy",
  unitPrice: 224.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158483/Duo-Intense-TX---Acido-Tranexamico---1.png?v=639245768358900000",
  productUrl: "https://www.creamy.com.br/intensetx-acidotranexamico/p",
  popularity: 66
 },
 {
  sku: "creamy-258",
  name: "Kit Antioleosidade",
  brand: "Creamy",
  unitPrice: 161.97,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158146/dupla-skincare-limpador-antioleosidade-calming-cream-protetor-solar-1.png?v=638960600187470000",
  productUrl: "https://www.creamy.com.br/kit-antioleosidade-1/p",
  popularity: 67
 },
 {
  sku: "creamy-257",
  name: "Duo Limpador Antioleosidade + Ácido Salicílico",
  brand: "Creamy",
  unitPrice: 139.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158142/dupla-skincare-limpador-antioleosidade-acido-salicilico-1.png?v=638960405302930000",
  productUrl: "https://www.creamy.com.br/duo-limpador-antioleosidade-salicilico/p",
  popularity: 68
 },
 {
  sku: "creamy-236",
  name: "Kit Firmador",
  brand: "Creamy",
  unitPrice: 463.13,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157947/kit-de-skincare-firmador-1.jpg?v=638902065122230000",
  productUrl: "https://www.creamy.com.br/kit-firmador-1/p",
  popularity: 69
 },
 {
  sku: "creamy-234",
  name: "Kit Anti-Idade",
  brand: "Creamy",
  unitPrice: 359.97,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157939/kit-de-skincare-anti-idade-1.png?v=638902063643400000",
  productUrl: "https://www.creamy.com.br/kit-anti-idade-1/p",
  popularity: 70
 },
 {
  sku: "creamy-225",
  name: "Rotina Cuidado Básico",
  brand: "Creamy",
  unitPrice: 161.03,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157902/rotina-skincare-cuidado-basico-creamy-1.jpg?v=638902041531000000",
  productUrl: "https://www.creamy.com.br/rotina-cuidado-basico-1/p",
  popularity: 71
 },
 {
  sku: "creamy-154",
  name: "Kit Anti-Aging 30+ Rotina Completa",
  brand: "Creamy",
  unitPrice: 429.42,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157392/01.png?v=638664301493230000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-30-mais-rotina-completa/p",
  popularity: 72
 },
 {
  sku: "creamy-130",
  name: "Duo Limpador Glicerinado + Protetor Solar",
  brand: "Creamy",
  unitPrice: 119.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158095/Duo-Limpador-Glicerinado---Protetor-Solar.jpg?v=639084019256300000",
  productUrl: "https://www.creamy.com.br/duo-limpador-glicerinado-protetor-solar/p",
  popularity: 73
 },
 {
  sku: "creamy-124",
  name: "Duo Niacinamide + Calming Cream",
  brand: "Creamy",
  unitPrice: 139.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158091/Duo-Niacinamide---Calming-Cream.jpg?v=639084018700230000",
  productUrl: "https://www.creamy.com.br/duo-niacinamide-calming-cream/p",
  popularity: 74
 },
 {
  sku: "creamy-123",
  name: "Duo Ácido Tranexâmico + Calming Cream",
  brand: "Creamy",
  unitPrice: 139.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158110/Duo-Acido-Tranexamico---Calming-Cream.jpg?v=639084018540670000",
  productUrl: "https://www.creamy.com.br/duo-tranexamico-calming-cream/p",
  popularity: 75
 },
 {
  sku: "creamy-110",
  name: "Duo Protetor Solar + Sérum Hidratante",
  brand: "Creamy",
  unitPrice: 119.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157556/01-cadastro-Duo-Protetor-Solar---Sérum-Hidratante.png?v=638709368272600000",
  productUrl: "https://www.creamy.com.br/duo-protetor-solar-e-serum-hidratante/p",
  popularity: 76
 },
 {
  sku: "creamy-95",
  name: "Duo Mandélico + Salicílico",
  brand: "Creamy",
  unitPrice: 169.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158093/Duo-Mandelico---Salicilico.jpg?v=639084016809100000",
  productUrl: "https://www.creamy.com.br/duo-mandelico-e-salicilico/p",
  popularity: 77
 },
 {
  sku: "creamy-93",
  name: "Duo Calming Cream + Vitamina C",
  brand: "Creamy",
  unitPrice: 149.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158106/Duo-Calming-Cream---Vitamina-C.jpg?v=639084016516030000",
  productUrl: "https://www.creamy.com.br/duo-calming-cream-e-vitamina-c/p",
  popularity: 78
 },
 {
  sku: "creamy-78",
  name: "Duo Peptide Retinol",
  brand: "Creamy",
  unitPrice: 289.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158090/Duo-Peptide---Retinol.jpg?v=639084015297200000",
  productUrl: "https://www.creamy.com.br/duo-peptide-retinol/p",
  popularity: 79
 },
 {
  sku: "creamy-72",
  name: "Duo para Pele Madura - Peptide Cream + Eye Cream",
  brand: "Creamy",
  unitPrice: 319.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158068/dupla-pele-madura-eye-cream-peptide-cream-creamy-1.jpg?v=638905264190200000",
  productUrl: "https://www.creamy.com.br/duo-peptide-eye-cream/p",
  popularity: 80
 },
 {
  sku: "creamy-277",
  name: "Kit Antirrugas Firmador",
  brand: "Creamy",
  unitPrice: 381.29,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158406/Kit-Antirrugas-Firmador---1.png?v=639154167573730000",
  productUrl: "https://www.creamy.com.br/kit-antirrugas-firmador/p",
  popularity: 81
 },
 {
  sku: "creamy-235",
  name: "Kit Controle de Poros",
  brand: "Creamy",
  unitPrice: 246.29,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157943/kit-de-skincare-controle-de-poros-1.jpg?v=638902064448870000",
  productUrl: "https://www.creamy.com.br/kit-controle-de-poros-1/p",
  popularity: 82
 },
 {
  sku: "creamy-232",
  name: "Kit Antiacne",
  brand: "Creamy",
  unitPrice: 246.29,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157935/kit-de-skincare-antiacne-1.jpg?v=638902059655700000",
  productUrl: "https://www.creamy.com.br/kit-antiacne-1/p",
  popularity: 83
 },
 {
  sku: "creamy-230",
  name: "Rotina para Pele Madura",
  brand: "Creamy",
  unitPrice: 397.85,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157921/rotina-de-skincare-pele-madura-1.jpg?v=638902050335570000",
  productUrl: "https://www.creamy.com.br/rotina-para-pele-madura-1/p",
  popularity: 84
 },
 {
  sku: "creamy-229",
  name: "Rotina para Pele Seca",
  brand: "Creamy",
  unitPrice: 274.71,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157916/rotina-de-skincare-pele-seca-1--1-.jpg?v=638906244298100000",
  productUrl: "https://www.creamy.com.br/rotina-para-pele-seca-1/p",
  popularity: 85
 },
 {
  sku: "creamy-227",
  name: "Rotina para Pele Mista",
  brand: "Creamy",
  unitPrice: 255.75,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157966/rotina-de-skincare-pele-mista-creamy-1--1-.png?v=638902558755470000",
  productUrl: "https://www.creamy.com.br/rotina-para-pele-mista-1/p",
  popularity: 86
 },
 {
  sku: "creamy-160",
  name: "Kit Anti-Aging 50+ Rotina Completa",
  brand: "Creamy",
  unitPrice: 599.42,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157398/01.png?v=638664304723400000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-50-mais-rotina-completa/p",
  popularity: 87
 },
 {
  sku: "creamy-144",
  name: "Duo Glicólico + Tranexâmico",
  brand: "Creamy",
  unitPrice: 169.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158102/Duo-Glicolico---Tranexamico.jpg?v=639084020475100000",
  productUrl: "https://www.creamy.com.br/duo-glicolico-tranexamico/p",
  popularity: 88
 },
 {
  sku: "creamy-109",
  name: "Duo Protetor Solar + Niacinamide",
  brand: "Creamy",
  unitPrice: 149.99,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158087/Duo-Protetor-Solar---Niacinamide.jpg?v=639084017609530000",
  productUrl: "https://www.creamy.com.br/duo-protetor-solar-e-niacinamide/p",
  popularity: 89
 },
 {
  sku: "creamy-96",
  name: "Duo Mandélico + Vitamina C",
  brand: "Creamy",
  unitPrice: 179.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158092/Duo-Mandelico---Vitamina-C.jpg?v=639084016958430000",
  productUrl: "https://www.creamy.com.br/duo-mandelico-e-vita-c/p",
  popularity: 90
 },
 {
  sku: "creamy-89",
  name: "Duo Calming Cream + Calming Body Cream",
  brand: "Creamy",
  unitPrice: 119.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158109/Duo-Calming-Cream---Calming-Body-Cream.jpg?v=639084015464200000",
  productUrl: "https://www.creamy.com.br/duo-calming-cream-e-calming-body-cream/p",
  popularity: 91
 },
 {
  sku: "creamy-56",
  name: "Rotina Antimanchas - Pele Seca ou Balanceada Rotina Antimanchas pele seca ou normal",
  brand: "Creamy",
  unitPrice: 393.64,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157655/1--2-.png?v=638834544361230000",
  productUrl: "https://www.creamy.com.br/rotina-antimanchas-seca/p",
  popularity: 92
 },
 {
  sku: "creamy-192",
  name: "KIT ESSENCIAL",
  brand: "Creamy",
  unitPrice: 200.72,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157434/01-cadastro-essential.png?v=638681640202400000",
  productUrl: "https://www.creamy.com.br/kit-rotina-essencial/p",
  popularity: 93
 },
 {
  sku: "creamy-190",
  name: "KIT TOP SELLERS",
  brand: "Creamy",
  unitPrice: 201.97,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157954/top-sellers-mandelico-calming-protetor-creamy-2.jpg?v=638902093174800000",
  productUrl: "https://www.creamy.com.br/kit-top-sellers/p",
  popularity: 94
 },
 {
  sku: "creamy-140",
  name: "Duo Vitamina C + Ácido Tranexâmico",
  brand: "Creamy",
  unitPrice: 189.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158084/Duo-Vitamina-C---Acido-Tranexamico.jpg?v=639084020194570000",
  productUrl: "https://www.creamy.com.br/duo-vitamina-c-acido-tranexanico/p",
  popularity: 95
 },
 {
  sku: "creamy-133",
  name: "Duo Limpador Glicerinado + Glicólico",
  brand: "Creamy",
  unitPrice: 139.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158097/Duo-Limpador-Glicerinado---Glicolico.jpg?v=639084019898670000",
  productUrl: "https://www.creamy.com.br/duo-limpador-glicerinado-glicolico/p",
  popularity: 96
 },
 {
  sku: "creamy-132",
  name: "Duo Limpador Glicerinado + Niacinamide",
  brand: "Creamy",
  unitPrice: 149.99,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158096/Duo-Limpador-Glicerinado---Niacinamide.jpg?v=639084019692630000",
  productUrl: "https://www.creamy.com.br/duo-limpador-glicerinado-niacinamide/p",
  popularity: 97
 },
 {
  sku: "creamy-122",
  name: "Duo para Acne - Glicointense Peel + Niacinamide B Complex 20%",
  brand: "Creamy",
  unitPrice: 189.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158074/dupla-skincare-acne-glicointense-peel-niacinamida-creamy-1.jpg?v=638905276481800000",
  productUrl: "https://www.creamy.com.br/duo-glicointense-niacinamide/p",
  popularity: 98
 },
 {
  sku: "creamy-101",
  name: "Refil Sérum Facial Vitamina C 30ml Refil Serum Facial Vitamina C 30ML - Creamy",
  brand: "Creamy",
  unitPrice: 79.99,
  unit: "un",
  category: "produtos antioxidante",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157958/refil-vitamina c-creamy-antioxidante-1.jpg?v=638902497618570000",
  productUrl: "https://www.creamy.com.br/refil-serum-facial-vitamina-c/p",
  popularity: 99
 },
 {
  sku: "creamy-97",
  name: "Duo Peptide Cream + Vitamina C",
  brand: "Creamy",
  unitPrice: 289.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158089/Duo-Peptide-Cream---Vitamina-C.jpg?v=639084017126930000",
  productUrl: "https://www.creamy.com.br/duo-peptide-cream-e-vita-c/p",
  popularity: 100
 },
 {
  sku: "creamy-63",
  name: "Rotina Anti-Aging Prevenção - Pele Oleosa ou Mista Rotina anti-aging prevenção pele oleosa ou mista",
  brand: "Creamy",
  unitPrice: 447.31,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157624/foto-1-Rotina-Anti-Aging-Prevencao---Pele-Oleosa-ou-Mista.png.png?v=638823921503030000",
  productUrl: "https://www.creamy.com.br/rotina-prevencao-oleosa/p",
  popularity: 101
 },
 {
  sku: "creamy-60",
  name: "Rotina Acne e Antioleosidade - Pele Seca ou Balanceada Rotina antiacne e antioleosidade para pele seca ou normal",
  brand: "Creamy",
  unitPrice: 312.59,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157656/1--3-.png?v=638834543958700000",
  productUrl: "https://www.creamy.com.br/rotina-antiacne-antioleosidade-seca/p",
  popularity: 102
 },
 {
  sku: "creamy-231",
  name: "Kit Essencial",
  brand: "Creamy",
  unitPrice: 198.93,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158000/kit-de-skincare-essencial-1--1-.jpg?v=638905304694030000",
  productUrl: "https://www.creamy.com.br/kit-essencial/p",
  popularity: 103
 },
 {
  sku: "creamy-228",
  name: "Rotina para Pele Sensível",
  brand: "Creamy",
  unitPrice: 293.65,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157672/Vitrine---Rotina-para-Pele-Sensivel_.png?v=638852426569430000",
  productUrl: "https://www.creamy.com.br/rotina-para-pele-sensivel-1/p",
  popularity: 104
 },
 {
  sku: "creamy-163",
  name: "Duo Ácido Glicólico + Refil",
  brand: "Creamy",
  unitPrice: 147.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158103/Duo-glicolico---refil.jpg?v=639046809259930000",
  productUrl: "https://www.creamy.com.br/duo-acido-glicolico-mais-refil-30g/p",
  popularity: 105
 },
 {
  sku: "creamy-161",
  name: "Duo Ácido Mandélico + Refil 30g",
  brand: "Creamy",
  unitPrice: 147.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158094/Duo-mandelico---refil.jpg?v=638974374659870000",
  productUrl: "https://www.creamy.com.br/duo-acido-mandelico-mais-refil-30g/p",
  popularity: 106
 },
 {
  sku: "creamy-157",
  name: "Kit Anti-Aging 40+ Rotina Completa",
  brand: "Creamy",
  unitPrice: 511.53,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157395/01.png?v=638664303145130000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-40-mais-rotina-completa/p",
  popularity: 107
 },
 {
  sku: "creamy-153",
  name: "Kit Anti-Aging 30+ Noturno",
  brand: "Creamy",
  unitPrice: 303.12,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157391/01.png?v=638664300544430000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-30-mais-noturno/p",
  popularity: 108
 },
 {
  sku: "creamy-145",
  name: "Duo Lático + Tranexâmico",
  brand: "Creamy",
  unitPrice: 159.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158100/Duo-Latico---Tranexamico.jpg?v=639084020614830000",
  productUrl: "https://www.creamy.com.br/duo-latico-tranexamico/p",
  popularity: 109
 },
 {
  sku: "creamy-131",
  name: "Duo Limpador Glicerinado + Calming Body Cream",
  brand: "Creamy",
  unitPrice: 129.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158099/Duo-Limpador-Glicerinado---Calming-Body-Cream.jpg?v=639084019394700000",
  productUrl: "https://www.creamy.com.br/duo-limpador-glicerinado-calming-body-cream/p",
  popularity: 110
 },
 {
  sku: "creamy-70",
  name: "Rotina de Manutenção - Pele Seca ou Balanceada Rotina de manutenção da pele seca ou normal",
  brand: "Creamy",
  unitPrice: 429.42,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157653/01--1-.png.png?v=638834343033270000",
  productUrl: "https://www.creamy.com.br/rotina-manutencao-seca/p",
  popularity: 111
 },
 {
  sku: "creamy-69",
  name: "Rotina de Manutenção - Pele Oleosa ou Mista Rotina de manutenção da pele oleosa ou mista",
  brand: "Creamy",
  unitPrice: 438.37,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157651/foto-01-Rotina-de-Manutencao---pele-oleosa-ou-mista‎‎-desktop.png.png?v=638829971593930000",
  productUrl: "https://www.creamy.com.br/rotina-manutencao-oleosa/p",
  popularity: 112
 },
 {
  sku: "creamy-64",
  name: "Rotina Anti-Aging Prevenção - Pele Seca ou Balanceada Rotina anti-aging prevenção pele seca ou normal",
  brand: "Creamy",
  unitPrice: 438.36,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157665/1--7-.png?v=638845700179670000",
  productUrl: "https://www.creamy.com.br/rotina-prevencao-seca/p",
  popularity: 113
 },
 {
  sku: "creamy-242",
  name: "Duo Ceramide Body Cream + Lip Incolor",
  brand: "Creamy",
  unitPrice: 113.9,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158111/dupla-ceramide-body-cream-hdratante-labial-sem-cor-creamy-1.jpg?v=638906891420500000",
  productUrl: "https://www.creamy.com.br/duo-ceramide-body-cream-lip-incolor/p",
  popularity: 114
 },
 {
  sku: "creamy-159",
  name: "Kit Anti-Aging 50+ Noturno",
  brand: "Creamy",
  unitPrice: 483.12,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157397/01.png?v=638664304451700000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-50-mais-noturno/p",
  popularity: 115
 },
 {
  sku: "creamy-71",
  name: "Rotina Anti-Aging Correção - Pele Oleosa ou Mista Rotina anti-aging rejuvenescimento pele oleosa ou mista",
  brand: "Creamy",
  unitPrice: 572.58,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157621/foto-1---Rotina-Anti-Aging-Correcao-para-Pele-Oleosa-ou-Mista.png.png?v=638823984032700000",
  productUrl: "https://www.creamy.com.br/rotina-correcao-oleosa/p",
  popularity: 116
 },
 {
  sku: "creamy-59",
  name: "Rotina Acne e Antioleosidade - Pele Sensível e Reativa Rotina Antiacne pele sensíve",
  brand: "Creamy",
  unitPrice: 342.45,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157654/1.png.png?v=638834505217900000",
  productUrl: "https://www.creamy.com.br/rotina-anticne-sensivel/p",
  popularity: 117
 },
 {
  sku: "creamy-57",
  name: "Rotina Antimanchas - Pele Sensível e Reativa Rotina Antimanchas pele sensível",
  brand: "Creamy",
  unitPrice: 429.42,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157664/1--6-.png?v=638845690522400000",
  productUrl: "https://www.creamy.com.br/rotina-antimanchas-sensivel/p",
  popularity: 118
 },
 {
  sku: "creamy-152",
  name: "Kit Anti-Aging 30+ Diurno",
  brand: "Creamy",
  unitPrice: 208.39,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157390/01-Anti-Aging-30--Diurno-miniatura.png?v=638664300148400000",
  productUrl: "https://www.creamy.com.br/kit-skincare-anti-aging-30-mais-diurno/p",
  popularity: 119
 },
 {
  sku: "creamy-142",
  name: "KIT LIP BALM THE COFFEE COLLECTION",
  brand: "Creamy",
  unitPrice: 110.49,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158286/the-coffee-collection-lip-bal-hidratante-labial-3.jpg?v=639072139070030000",
  productUrl: "https://www.creamy.com.br/kit-the-coffe-colletion/p",
  popularity: 120
 },
 {
  sku: "creamy-158",
  name: "Kit Anti-Aging 50+ Diurno",
  brand: "Creamy",
  unitPrice: 331.54,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157396/01.png?v=638664304145070000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-50-mais-diurno/p",
  popularity: 121
 },
 {
  sku: "creamy-155",
  name: "Kit Anti-Aging 40+ Diurno",
  brand: "Creamy",
  unitPrice: 208.39,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157393/01.png?v=638664302464000000",
  productUrl: "https://www.creamy.com.br/kit-anti-aging-40-mais-diurno/p",
  popularity: 122
 },
 {
  sku: "creamy-102",
  name: "Refil Sérum Facil Ácido Lático 30ml Refil Serum Facial Acido Lático 30ML - Creamy",
  brand: "Creamy",
  unitPrice: 69.99,
  unit: "un",
  category: "produtos antiacne",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158022/refil-acido-latico-creamy-amarelinho-acne-1.jpg?v=638902581832830000",
  productUrl: "https://www.creamy.com.br/refil-serum-facil-acido-latico/p",
  popularity: 123
 },
 {
  sku: "creamy-62",
  name: "Rotina Pele Extremamente Sensível ou Reativa - Todos os Tipos de Pele Rotina pele extremamente sensível ou reativa",
  brand: "Creamy",
  unitPrice: 388.39,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157657/1--5-.png?v=638834574372870000",
  productUrl: "https://www.creamy.com.br/rotina-extremamente-sensivel/p",
  popularity: 124
 },
 {
  sku: "creamy-165",
  name: "DUO SÉRUM FACIAL ÁCIDO LÁTICO + REFIL 30G",
  brand: "Creamy",
  unitPrice: 129.98,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158101/Duo-latico---refil.jpg?v=639084021417370000",
  productUrl: "https://www.creamy.com.br/duo-serum-acido-latico-mais-refil-30g-1/p",
  popularity: 125
 },
 {
  sku: "creamy-162",
  name: "DUO SÉRUM FACIAL VITAMINA C + REFIL 30ML",
  brand: "Creamy",
  unitPrice: 184.97,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/158083/Duo-vitamina-c---refil.jpg?v=639084021019900000",
  productUrl: "https://www.creamy.com.br/duo-serum-vitamina-c-mais-refil-30ml/p",
  popularity: 126
 },
 {
  sku: "creamy-86",
  name: "Skin Cycling Program",
  brand: "Creamy",
  unitPrice: 372.14,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/156712/Combo-Skin-Cycling---1.jpg?v=638321315177870000",
  productUrl: "https://www.creamy.com.br/skin-cycling-program/p",
  popularity: 127
 },
 {
  sku: "creamy-68",
  name: "Rotina Anti-Aging Correção - Pele Reativa e Sensível Rotina anti-aging rejuvenescimento pele reativa ou sensível",
  brand: "Creamy",
  unitPrice: 511.53,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157667/1--11-.png?v=638845715501700000",
  productUrl: "https://www.creamy.com.br/rotina-correcao-sensivel/p",
  popularity: 128
 },
 {
  sku: "creamy-65",
  name: "Rotina Anti-Aging Prevenção - Pele Reativa e Sensível Rotina anti-aging prevenção pele reativa ou sensível",
  brand: "Creamy",
  unitPrice: 581.52,
  unit: "un",
  category: "produtos combos",
  imageUrl: "https://creamy.vteximg.com.br/arquivos/ids/157666/1--8-.png?v=638845709560600000",
  productUrl: "https://www.creamy.com.br/rotina-prevencao-sensivel/p",
  popularity: 129
 }
];
